site_name: Cozy Developer Documentation
docs_dir: src
site_url: https://docs.cozy.io/
site_dir: docs/en
site_favicon: img/favicon.png
repo_url: https://github.com/cozy/cozy.github.io/
edit_uri: edit/dev/src/
site_description: Cozy documentation
site_author: CozyCloud - https://cozy.io
extra_javascript:
- extra.js
nav:
- Home: index.md
- Tutorials:
  - Create Your Application: tutorials/app.md
  - Develop a Connector: tutorials/konnector.md
  - Self-Host on Debian: tutorials/selfhost-debian.md
- How-to:
  - Dev:
    - Run an App in a Cozy using Docker: howTos/dev/runCozyDocker.md
    - Use Hot Module Replacement in Your App: howTos/dev/hmr.md
    - Make a Mobile App Using Cordova: howTos/dev/cordova.md
    - Connect a Mobile App to Your Local Stack: howTos/dev/connect-mobile-app-local-stack.md
    - Send and Receive E-mails in Development: howTos/dev/sendmail.md
    - Our Front-End Git Flow: references/git-flow.md
    - Technical introduction to the Cozy platform: references/tech-intro.md
  - Synchronize:
    - Install Cozy Drive on GNU/Linux: howTos/sync/linux.md
- Stack and tools:
  - eslint-config-cozy-app: eslint-config-cozy-app/README.md
  - commitlint-config-cozy: commitlint-config-cozy/README.md
  - cozy-stack:
    - README: cozy-stack/README.md
    - Usage:
      - Install the cozy-stack: cozy-stack/INSTALL.md
      - Configuration file: cozy-stack/config.md
      - Managing Instances: cozy-stack/instance.md
      - Security: cozy-stack/security.md
      - Manpages of the command-line tool: cozy-stack/cli/cozy-stack.md
    - How-to guides for developpers:
      - Develop a client-side app: cozy-stack/client-app-dev.md
      - Running and building Docker images: cozy-stack/docker.md
      - Adding a new doctype: cozy-stack/doctype.md
      - Working with the stack assets: cozy-stack/assets.md
      - Build a release: cozy-stack/release.md
      - The contributing guide: cozy-stack/CONTRIBUTING.md
    - Explanations:
      - Sharing design: cozy-stack/sharing-design.md
      - Workflow of the konnectors: cozy-stack/konnectors-workflow.md
    - List of services:
      - /auth - Authentication & OAuth: cozy-stack/auth.md
      - /apps - Applications Management: cozy-stack/apps.md
      - ' /apps - Apps registry': cozy-stack/registry.md
      - ' /apps - Konnectors': cozy-stack/konnectors.md
      - /data - Data System: cozy-stack/data-system.md
      - ' /data - Mango': cozy-stack/mango.md
      - ' /data - CouchDB Quirks': cozy-stack/couchdb-quirks.md
      - ' /data - PouchDB Quirks': cozy-stack/pouchdb-quirks.md
      - /files - Virtual File System: cozy-stack/files.md
      - ' /files - References of documents in VFS': cozy-stack/references-docs-in-vfs.md
      - /intents - Intents: cozy-stack/intents.md
      - /jobs - Jobs: cozy-stack/jobs.md
      - ' /jobs - Workers': cozy-stack/workers.md
      - /move - Move, export and import an instance: cozy-stack/move.md
      - /notifications - Notifications: cozy-stack/notifications.md
      - /public - Public: cozy-stack/public.md
      - /permissions - Permissions: cozy-stack/permissions.md
      - /realtime - Realtime: cozy-stack/realtime.md
      - /remote - Proxy for remote data/API: cozy-stack/remote.md
      - /settings - Settings: cozy-stack/settings.md
      - ' /settings - Terms of Services': cozy-stack/user-action-required.md
      - /sharings - Sharing: cozy-stack/sharing.md
  - cozy-app-publish: cozy-app-publish/README.md
  - babel-preset-cozy-app: babel-preset-cozy-app/README.md
  - konitor: konitor/cli.md
  - cozy-doctypes:
    - README: cozy-doctypes/docs/README.md
    - Accounts: cozy-doctypes/docs/io.cozy.accounts.md
    - Apps: cozy-doctypes/docs/io.cozy.apps.md
    - Banking doctypes: cozy-doctypes/docs/io.cozy.bank.md
    - Bills: cozy-doctypes/docs/io.cozy.bills.md
    - Connectors: cozy-doctypes/docs/io.cozy.konnectors.md
    - Contacts: cozy-doctypes/docs/io.cozy.contacts.md
    - Files: cozy-doctypes/docs/io.cozy.files.md
    - Files metadata: cozy-doctypes/docs/io.cozy.files_metadata.md
    - Identities: cozy-doctypes/docs/io.cozy.identities.md
    - Notifications: cozy-doctypes/docs/io.cozy.notifications.md
    - Remote requests: cozy-doctypes/docs/io.cozy.remote.requests.md
    - Session logins: cozy-doctypes/docs/io.cozy.sessions.logins.md
    - Permissions: cozy-doctypes/docs/io.cozy.permissions.md
    - Photos Albums: cozy-doctypes/docs/io.cozy.photos.albums.md
    - Procedures: cozy-doctypes/docs/io.cozy.procedures.md
    - Sessions Logins: cozy-doctypes/docs/io.cozy.sessions.logins.md
    - Settings: cozy-doctypes/docs/io.cozy.settings.md
    - Sharings: cozy-doctypes/docs/io.cozy.sharings.md
    - Accounts Types: cozy-doctypes/docs/io.cozy.account_types.md
    - Autocategorization: cozy-doctypes/docs/cc.cozycloud.autocategorization.md
    - Exports: cozy-doctypes/docs/io.cozy.exports.md
    - Jobs: cozy-doctypes/docs/io.cozy.jobs.md
    - OAuth Clients: cozy-doctypes/docs/io.cozy.oauth.clients.md
    - OAuth Access Codes: cozy-doctypes/docs/io.cozy.oauth.access_codes.md
    - Triggers: cozy-doctypes/docs/io.cozy.triggers.md
    - Triggers state: cozy-doctypes/docs/io.cozy.triggers.state.md
    - Remote requests: cozy-doctypes/docs/io.cozy.remote.requests.md
    - Sessions: cozy-doctypes/docs/io.cozy.sessions.md
    - Shared: cozy-doctypes/docs/io.cozy.shared.md
    - Terms: cozy-doctypes/docs/io.cozy.terms.md
    - Bets Unibet: cozy-doctypes/docs/com.unibet.bets.md
  - cozy-ui: cozy-ui/README.md
  - cozy-device-helper: cozy-device-helper/README.md
  - cozy-client:
    - Getting started: cozy-client/getting-started.md
    - Using relationship: cozy-client/relationships.md
    - cozyMetadata maintenance: cozy-client/metadata.md
    - React integration: cozy-client/react-integration.md
    - Other details: cozy-client/details.md
    - Cozy Client API: cozy-client/api/cozy-client.md
    - Cozy Pouch Link API: cozy-client/api/cozy-pouch-link.md
    - Cozy Stack Client API: cozy-client/api/cozy-stack-client.md
  - cozy-realtime: cozy-realtime/README.md
  - cozy-konnector-libs:
    - API: cozy-konnector-libs/api.md
    - CLI: cozy-konnector-libs/cli.md
    - Develop: cozy-konnector-libs/dev.md
    - Errors: cozy-konnector-libs/errors.md
    - Operation linking: cozy-konnector-libs/operation-linking.md
    - Synchronization: cozy-konnector-libs/synchronization.md
  - cozy-apps-registry: cozy-apps-registry/README.md
  - cozy-flags: cozy-flags/README.md
  - cozy-client-js:
    - README: cozy-client-js/README.md
    - Introduction: cozy-client-js/intro.md
    - Transition from cozy-browser-sdk: cozy-client-js/browser-sdk-transition.md
    - How to support offline: cozy-client-js/offline.md
    - OAuth guide: cozy-client-js/oauth.md
    - Authentication API: cozy-client-js/auth-api.md
    - Data System API: cozy-client-js/data-api.md
    - Files API: cozy-client-js/files-api.md
    - Jobs API: cozy-client-js/jobs-api.md
    - Intents API: cozy-client-js/intents-api.md
    - Settings API: cozy-client-js/settings-api.md
    - Sharing API: cozy-client-js/sharing-api.md
theme:
  custom_dir: cozy-theme
  name: material
  palette:
    primary: blue
    accent: blue
  logo:
    icon: cloud
  font:
    text: Lato
    code: Ubuntu Mono
markdown_extensions:
- admonition
- codehilite
- extra
- footnotes
- meta
- sane_lists
- smarty
- toc:
    permalink: true
extra:
  search:
    tokenizer: '[^a-zа-яё0-9\-]'
  outside_docs:
  - name: cozy-app-publish
    repo: https://github.com/cozy/cozy-app-publish.git
    subdir: .
  - name: cozy-apps-registry
    repo: https://github.com/cozy/cozy-apps-registry.git
    subdir: .
  - name: cozy-client
    repo: https://github.com/cozy/cozy-client.git
    subdir: docs
  - name: cozy-client-js
    repo: https://github.com/cozy/cozy-client-js.git
    subdir: docs
  - name: cozy-ui
    repo: https://github.com/cozy/cozy-ui.git
    subdir: docs
  - name: cozy-doctypes
    repo: https://github.com/cozy/cozy-doctypes.git
    subdir: .
  - name: cozy-konnector-libs
    repo: https://github.com/konnectors/libs.git
    subdir: packages/cozy-konnector-libs/docs
  - name: cozy-scripts
    repo: https://github.com/CPatchane/create-cozy-app.git
    subdir: packages/cozy-scripts/docs
  - name: cozy-stack
    repo: https://github.com/cozy/cozy-stack.git
    subdir: docs
  - name: konitor
    repo: https://github.com/konnectors/konitor.git
    subdir: docs
  - name: babel-preset-cozy-app
    repo: https://github.com/cozy/cozy-libs.git
    subdir: packages/babel-preset-cozy-app
  - name: commitlint-config-cozy
    repo: https://github.com/cozy/cozy-libs.git
    subdir: packages/commitlint-config-cozy
  - name: cozy-device-helper
    repo: https://github.com/cozy/cozy-libs.git
    subdir: packages/cozy-device-helper
  - name: eslint-config-cozy-app
    repo: https://github.com/cozy/cozy-libs.git
    subdir: packages/eslint-config-cozy-app
  - name: cozy-flags
    repo: https://github.com/cozy/cozy-libs.git
    subdir: packages/cozy-flags
  - name: cozy-realtime
    repo: https://github.com/cozy/cozy-libs.git
    subdir: packages/cozy-realtime
